name: Build

on:
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Check Format
      run: cargo fmt -- --check
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'latest'
    - uses: actions/setup-node@v1
      with:
        node-version: '15'
    - name: Init Web app
      working-directory: web/
      run: yarn install
    - name: Build web app
      working-directory: web/
      run: yarn build
    - name: Test web app
      working-directory: web/
      run: yarn test # no effective test so far, just to make sure it lints & builds well
